#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

cd "$(dirname "$0")/.."
PROJECT_ROOT="$(pwd)"
SECRETS_DIR="C:/Users/user/.secrets/Xana Plus App/Firebase"
APP_PACKAGE="ke.co.xana.xanaplus"
EAS="npx --yes eas-cli@latest"

banner "Xana Plus push notifications"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Expo account"
say "Push notifications go out through Expo's push service, so the project needs a"
say "free Expo account. The same account is used later for app-store builds."
open_url "https://expo.dev/signup"
step "Sign up (it@xanalife.com or any address you control)."
step "Open the confirmation email and verify the account."
pause "Account created and verified? Press Enter."

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Sign in on this machine"
say "This signs the Expo CLI in and stores its token in your user profile, not in"
say "the repo. It prints a link and asks for your email and password."
$EAS login
say "Checking the account it landed on..."
$EAS whoami || warn "not signed in yet, run this stage again"
ask EXPO_ACCOUNT "Expo username printed above:"

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Create the EAS project"
say "This links this folder to an EAS project and writes its id into app.json."
note "Answer yes when it offers to create the project."
$EAS init
node -e 'const c=require("./app.json");const id=c.expo&&c.expo.extra&&c.expo.extra.eas&&c.expo.extra.eas.projectId;console.log(id?("  projectId = "+id):"  projectId MISSING - run eas init again");'

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Firebase (Android push)"
say "Android push travels through Firebase Cloud Messaging. Two files come out of"
say "Firebase: one public config file for the app, one private key for sending."
open_url "https://console.firebase.google.com/"
step "Create a project (name it Xana Plus)."
step "Add an Android app with package name: $APP_PACKAGE"
step "Download google-services.json and save it into this folder:"
note "  $PROJECT_ROOT"
step "Then: Project settings > Service accounts > Generate new private key,"
step "and save that JSON outside the repo (it is a secret)."
mkdir -p "$SECRETS_DIR"
note "  suggested: $SECRETS_DIR"
ask GOOGLE_SERVICES_PATH "Path to google-services.json [./google-services.json]:"
GOOGLE_SERVICES_PATH="${GOOGLE_SERVICES_PATH:-./google-services.json}"
if [[ -f "$GOOGLE_SERVICES_PATH" ]]; then
  node -e 'const fs=require("fs");const p="./app.json";const c=JSON.parse(fs.readFileSync(p,"utf8"));c.expo.android=c.expo.android||{};c.expo.android.googleServicesFile=process.argv[1];fs.writeFileSync(p,JSON.stringify(c,null,2)+"\n");console.log("  app.json: android.googleServicesFile =",process.argv[1]);' "$GOOGLE_SERVICES_PATH"
else
  warn "not found at $GOOGLE_SERVICES_PATH - download it, then re-run this stage"
fi
ask FCM_KEY_PATH "Path to the Firebase private-key JSON:"
say "Now hand that key to Expo so its push service may send to your app."
$EAS credentials
note "In the menu pick:  Android > production > Google Service Account >"
note "  Manage your Google Service Account Key for Push Notifications (FCM V1) >"
note "  Set up a Google Service Account Key for Push Notifications (FCM V1) >"
note "  Upload a new service account key > choose $FCM_KEY_PATH"
pause "Key uploaded? Press Enter."

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Development build"
say "Push does not work in Expo Go on Android (SDK 53 and later), so the phone needs"
say "a development build. This installs the client that build needs."
npm install expo-dev-client@~57.0.19
say "Now building on Expo's servers. This usually takes 10 to 20 minutes."
$EAS build --profile development --platform android
step "When it finishes, the terminal prints a build-page link."
step "Open that link on the phone (or scan its QR) and install the APK."
pause "Installed on the phone? Press Enter."

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Test it"
say "Start the dev server and leave it running:"
note "  npx expo start --port 8090"
say "Open the Xana Plus development build on the phone and sign in:"
note "  0700 000 000  /  123456"
note "The app asks for notification permission, then saves a token."
warn "The token only saves once the push backend is deployed to Supabase (on hold)."
say "Once it is, send a test push, or use Expo's own tool:"
note "  curl -X POST https://yinlbtldfojobuwddpsj.supabase.co/functions/v1/send-push \\"
note "    -H 'Content-Type: application/json' \\"
note "    -H 'x-sync-secret: <BC_SYNC_SECRET>' \\"
note "    -d '{\"userIds\":[\"<user-uuid>\"],\"title\":\"Test\",\"body\":\"Hello\"}'"
open_url "https://expo.dev/notifications"

finish
